import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { BadgeCheck, BookOpen, Check, ChevronLeft, ClipboardCheck, Crown, GraduationCap, Home as HomeIcon, KeyRound, Languages, Loader2, LockKeyhole, LogIn, LogOut, Medal, MessageCircleHeart, Plus, ShieldCheck, Sparkles, Star, Target, Trophy, UserRound, WandSparkles } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type Language = "en" | "ar";
type Screen = "welcome" | "parent" | "children";
type ChildKey = "sandy" | "celia";
type Category = "academic" | "household" | "hygiene" | "organization";

const copy = {
  en: {
    brand: "Family Growth Hub", eyebrow: "A LITTLE EFFORT · A LOT OF GROWTH", heroTitle: "Growing great habits,\ntogether.", heroText: "A joyful home base for Sandy and Celia to build routines, celebrate progress, and make every small win count.",
    parentDoor: "Parent space", childrenDoor: "Children's space", signedIn: "Parent account", signOut: "Sign out", signIn: "Sign in as parent", parentHint: "Parents can manage tasks, reviews, and academic progress.",
    welcomeBack: "Welcome back", parentPanel: "Parent dashboard", overview: "Family overview", createTask: "Create a task", reviewWork: "Review work", trackLearning: "Track learning", security: "Account access",
    sandy: "Sandy", celia: "Celia", years: "years", points: "points", completed: "completed", weeklyProgress: "Weekly progress", openTasks: "tasks to do", everythingDone: "All caught up!", setPin: "Set access PIN", changePin: "Change access PIN", pinReady: "PIN ready", pinNeeded: "PIN not set", selectChild: "Select child", privatePin: "Private PIN", enterPin: "Enter a 4–8 digit PIN", continue: "Continue", childLogin: "Child sign in", childIntro: "Choose your account and enter your private PIN.",
    todayTasks: "My tasks", yourProgress: "Your progress", keepGoing: "Keep going — every task makes you stronger.", markDone: "Mark complete", complete: "Completed", reviewed: "Reviewed", due: "Due", noDue: "Any time", noTasks: "Your task list is clear. Enjoy your win!", earned: "Earned", badges: "Badges", school: "School progress", noGrades: "Your learning moments will appear here.",
    taskTitle: "Task title", taskDescription: "A helpful detail (optional)", category: "Task type", deadline: "Deadline", reward: "Points reward", assignTo: "Assign to", addTask: "Add task", taskCreated: "Task created for", taskCompleteToast: "Wonderful work! Your points have been added.",
    academic: "Academic", household: "Household", hygiene: "Personal hygiene", organization: "Organization", first10: "First 10 tasks", first10Text: "You completed your first ten tasks!", perfectWeek: "Perfect week", perfectWeekText: "Every task finished on time this week.",
    completedTasks: "Completed tasks", chooseTask: "Choose a completed task", chooseTaskHelp: "Only completed tasks awaiting feedback appear here.", rating: "Star rating", encouragingNote: "Encouraging note", writeNote: "Write a kind message...", submitReview: "Share review", reviewSaved: "Review saved", noReviews: "There are no completed tasks awaiting review.",
    subject: "Subject", assessment: "Assessment / test", score: "Score", total: "Out of", recordGrade: "Record grade", gradeSaved: "Grade recorded", recentGrades: "Recent results", percent: "result", pinSaved: "PIN updated", fillAll: "Please complete the required fields.", invalidPin: "Use 4 to 8 digits for the PIN.",
    childPrivacy: "Only the selected child’s tasks and progress are visible here.", notAdmin: "This parent account does not yet have family administrator access.", setPinsFirst: "Set a private PIN from the parent dashboard before a child signs in.", back: "Back", language: "العربية", status: "Status", review: "Parent review", secure: "Private family space", readyToGrow: "Ready to grow?", goodMorning: "You can do this!", taskType: "Task type",
  },
  ar: {
    brand: "بيت الإنجاز", eyebrow: "مجهود بسيط · نمو كبير", heroTitle: "نبني عادات رائعة،\nمعًا.", heroText: "مساحة منزلية مبهجة لساندي وسيليا لبناء الروتين، والاحتفال بالتقدّم، وجعل كل إنجاز صغير مهمًا.",
    parentDoor: "مساحة الوالدين", childrenDoor: "مساحة الأطفال", signedIn: "حساب الوالدين", signOut: "تسجيل الخروج", signIn: "دخول الوالدين", parentHint: "يمكن للوالدين إدارة المهام والتقييمات والتقدّم الدراسي.",
    welcomeBack: "أهلًا بعودتك", parentPanel: "لوحة الوالدين", overview: "نظرة عائلية", createTask: "إنشاء مهمة", reviewWork: "تقييم الإنجاز", trackLearning: "متابعة الدراسة", security: "دخول الحساب",
    sandy: "ساندي", celia: "سيليا", years: "سنة", points: "نقطة", completed: "مكتملة", weeklyProgress: "تقدم الأسبوع", openTasks: "مهام متبقية", everythingDone: "أنجزتِ كل شيء!", setPin: "تعيين رقم دخول", changePin: "تغيير رقم الدخول", pinReady: "رقم الدخول جاهز", pinNeeded: "لم يُضبط الرقم", selectChild: "اختاري الطفلة", privatePin: "رقم دخول خاص", enterPin: "أدخلي ٤–٨ أرقام", continue: "متابعة", childLogin: "دخول الطفلة", childIntro: "اختاري حسابك وأدخلي رقم الدخول الخاص بك.",
    todayTasks: "مهامي", yourProgress: "تقدّمك", keepGoing: "واصلي التقدّم — كل مهمة تجعلك أقوى.", markDone: "إكمال المهمة", complete: "مكتملة", reviewed: "تم التقييم", due: "الموعد", noDue: "في أي وقت", noTasks: "قائمة مهامك فارغة. استمتعي بإنجازك!", earned: "تم كسبها", badges: "الشارات", school: "التقدم الدراسي", noGrades: "ستظهر هنا لحظات تعلّمك.",
    taskTitle: "عنوان المهمة", taskDescription: "تفصيل مساعد (اختياري)", category: "نوع المهمة", deadline: "الموعد النهائي", reward: "نقاط المكافأة", assignTo: "تُسند إلى", addTask: "إضافة المهمة", taskCreated: "تم إنشاء مهمة لـ", taskCompleteToast: "عمل رائع! تمت إضافة نقاطك.",
    academic: "دراسي", household: "منزلي", hygiene: "نظافة شخصية", organization: "تنظيم", first10: "أول ١٠ مهام", first10Text: "أكملتِ أول عشر مهام لك!", perfectWeek: "أسبوع مثالي", perfectWeekText: "أنهيتِ كل مهام الأسبوع في موعدها.",
    completedTasks: "المهام المكتملة", chooseTask: "اختاري مهمة مكتملة", chooseTaskHelp: "تظهر هنا المهام المكتملة التي تنتظر التقييم فقط.", rating: "تقييم بالنجوم", encouragingNote: "رسالة تشجيع", writeNote: "اكتبي رسالة لطيفة...", submitReview: "إرسال التقييم", reviewSaved: "حُفظ التقييم", noReviews: "لا توجد مهام مكتملة تنتظر التقييم.",
    subject: "المادة", assessment: "التقييم أو الاختبار", score: "الدرجة", total: "من", recordGrade: "تسجيل الدرجة", gradeSaved: "تم تسجيل الدرجة", recentGrades: "أحدث النتائج", percent: "النتيجة", pinSaved: "تم تحديث الرقم", fillAll: "من فضلك املئي الحقول المطلوبة.", invalidPin: "استخدمي من ٤ إلى ٨ أرقام لرقم الدخول.",
    childPrivacy: "لا تظهر هنا إلا مهام الطفلة المختارة وتقدمها.", notAdmin: "لا يملك حساب الوالدين هذا صلاحية إدارة العائلة بعد.", setPinsFirst: "عيّنوا رقم دخول خاصًا من لوحة الوالدين قبل دخول الطفلة.", back: "رجوع", language: "English", status: "الحالة", review: "تقييم الوالدين", secure: "مساحة عائلية خاصة", readyToGrow: "مستعدون للنمو؟", goodMorning: "أنتِ تستطيعين!", taskType: "نوع المهمة",
  },
} as const;

const categoryIcons: Record<Category, typeof BookOpen> = { academic: BookOpen, household: HomeIcon, hygiene: Sparkles, organization: ClipboardCheck };
const childAccent: Record<ChildKey, string> = { sandy: "from-pink-400 to-rose-300", celia: "from-violet-400 to-indigo-300" };

type TaskView = { id: number; title: string; description: string | null; category: Category; dueDate: Date | null; points: number; status: "open" | "completed" | "reviewed"; completedAt: Date | null; review: { rating: number; comment: string | null } | null };
type GradeView = { id: number; subject: string; assessment: string; score: number; outOf: number; recordedAt: Date };
type BadgeView = { id: number; code: "first_10_tasks" | "perfect_week"; awardedAt: Date };
type ChildView = { child: { id: number; childKey: ChildKey; displayName: string; age: number; points: number; hasPin: boolean }; tasks: TaskView[]; grades: GradeView[]; badges: BadgeView[]; progress: number; completedCount: number };

function fmtDate(value: Date | string | null, lang: Language) {
  if (!value) return null;
  return new Intl.DateTimeFormat(lang === "ar" ? "ar-EG" : "en-US", { weekday: "short", month: "short", day: "numeric" }).format(new Date(value));
}

function displayKid(key: ChildKey, lang: Language) { return copy[lang][key]; }

function KidAvatar({ kid, size = "md" }: { kid: ChildKey; size?: "sm" | "md" | "lg" }) {
  const dimensions = { sm: "h-9 w-9 text-sm", md: "h-12 w-12 text-lg", lg: "h-20 w-20 text-3xl" }[size];
  return <div className={`grid ${dimensions} shrink-0 place-items-center rounded-[1.3rem] bg-gradient-to-br ${childAccent[kid]} font-bold text-white shadow-lg shadow-indigo-950/20`}>{kid === "sandy" ? "S" : "C"}</div>;
}

function Pill({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <span className={`inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-2.5 py-1 text-xs font-semibold text-white ${className}`}>{children}</span>;
}

function TaskCategoryPill({ category, lang }: { category: Category; lang: Language }) {
  const Icon = categoryIcons[category];
  return <Pill><Icon className="h-3.5 w-3.5" />{copy[lang][category]}</Pill>;
}

function TaskCard({ task, lang, childMode, onComplete }: { task: TaskView; lang: Language; childMode?: boolean; onComplete?: () => void }) {
  const t = copy[lang];
  const isDone = task.status !== "open";
  return <article className={`rounded-3xl border p-4 ${task.status === "open" ? "task-status-open bg-white/[.08]" : task.status === "completed" ? "task-status-completed" : "task-status-reviewed"}`}>
    <div className="flex items-start gap-3">
      <div className={`grid h-10 w-10 shrink-0 place-items-center rounded-2xl ${isDone ? "bg-emerald-300 text-indigo-950" : "bg-white/13 text-white"}`}>
        {isDone ? <Check className="h-5 w-5 stroke-[3]" /> : <Target className="h-5 w-5" />}
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-start justify-between gap-2"><h4 className={`font-bold leading-tight ${isDone ? "text-white/90" : "text-white"}`}>{task.title}</h4><TaskCategoryPill category={task.category} lang={lang} /></div>
        {task.description && <p className="mt-1.5 text-sm leading-6 text-white/70">{task.description}</p>}
        <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-2 text-xs text-white/73">
          <span className="inline-flex items-center gap-1"><Sparkles className="h-3.5 w-3.5 text-amber-200" />+{task.points} {t.points}</span>
          <span>{task.dueDate ? `${t.due}: ${fmtDate(task.dueDate, lang)}` : t.noDue}</span>
        </div>
        {task.review && <div className="mt-3 rounded-2xl bg-slate-950/20 p-3"><div className="flex items-center gap-1 text-amber-200">{Array.from({ length: task.review.rating }).map((_, i) => <Star key={i} className="h-3.5 w-3.5 fill-current" />)}<span className="ms-1 text-xs font-semibold text-white/80">{t.review}</span></div>{task.review.comment && <p className="mt-1.5 text-sm italic text-white/80">“{task.review.comment}”</p>}</div>}
        {childMode && task.status === "open" && <Button onClick={onComplete} className="round-button mt-4 h-10 w-full rounded-2xl bg-gradient-to-r from-amber-300 to-orange-300 font-bold text-violet-950 hover:from-amber-200 hover:to-orange-200"><Check className="me-2 h-4 w-4" />{t.markDone}</Button>}
      </div>
    </div>
  </article>;
}

function BadgeTile({ badge, lang }: { badge: BadgeView; lang: Language }) {
  const t = copy[lang];
  const first = badge.code === "first_10_tasks";
  return <div className="flex min-w-[138px] flex-1 items-center gap-3 rounded-2xl border border-white/20 bg-white/[.09] p-3"><div className={`grid h-10 w-10 place-items-center rounded-2xl ${first ? "bg-amber-300 text-violet-950" : "bg-fuchsia-300 text-violet-950"}`}>{first ? <Medal className="h-5 w-5" /> : <Trophy className="h-5 w-5" />}</div><div className="min-w-0"><p className="text-sm font-bold text-white">{first ? t.first10 : t.perfectWeek}</p><p className="mt-0.5 text-xs leading-4 text-white/65">{first ? t.first10Text : t.perfectWeekText}</p></div></div>;
}

function ChildDashboard({ data, lang, onBack }: { data: ChildView; lang: Language; onBack: () => void }) {
  const t = copy[lang];
  const utils = trpc.useUtils();
  const completeTask = trpc.family.child.completeTask.useMutation({
    onSuccess: () => { toast.success(t.taskCompleteToast); void utils.family.child.me.invalidate(); },
    onError: () => toast.error(t.fillAll),
  });
  const kid = data.child.childKey;
  const openTasks = data.tasks.filter(task => task.status === "open");
  return <section className="mx-auto max-w-6xl px-4 pb-16 pt-5 sm:px-6 lg:px-8">
    <div className="mb-6 flex items-center justify-between gap-4"><button onClick={onBack} className="round-button inline-flex items-center gap-1.5 text-sm font-semibold text-white/80 hover:text-white"><ChevronLeft className="h-4 w-4 rtl:rotate-180" />{t.back}</button><Pill><LockKeyhole className="h-3.5 w-3.5" />{t.childPrivacy}</Pill></div>
    <div className="glass appear rounded-[2rem] p-5 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><KidAvatar kid={kid} size="lg" /><div><p className="wide-label text-[10px] text-white/65">{t.goodMorning}</p><h2 className="hero-title mt-1 text-4xl font-extrabold text-white sm:text-5xl">{displayKid(kid, lang)}</h2><p className="mt-1 text-white/75">{t.keepGoing}</p></div></div><div className="rounded-3xl bg-white/[.11] px-6 py-4 text-center"><p className="text-xs font-semibold text-white/65">{t.points.toUpperCase()}</p><p className="mt-1 text-4xl font-extrabold text-amber-200">{data.child.points}</p></div></div>
      <div className="mt-7 grid gap-4 md:grid-cols-[1.4fr_.9fr]"><div className="rounded-3xl bg-slate-950/[.19] p-5"><div className="flex items-center justify-between"><p className="font-bold text-white">{t.yourProgress}</p><span className="font-extrabold text-amber-200">{data.progress}%</span></div><div className="progress-track mt-3"><div className="progress-fill" style={{ width: `${data.progress}%` }} /></div><p className="mt-3 text-sm text-white/68">{data.completedCount} {t.completed} · {openTasks.length} {t.openTasks}</p></div><div className="rounded-3xl bg-slate-950/[.19] p-5"><p className="font-bold text-white">{t.badges}</p>{data.badges.length ? <div className="mt-3 flex flex-wrap gap-2">{data.badges.map(badge => <BadgeTile key={badge.id} badge={badge} lang={lang} />)}</div> : <p className="mt-3 text-sm leading-6 text-white/67">{t.first10Text}</p>}</div></div>
    </div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1.28fr_.72fr]"><div className="glass delayed-1 appear rounded-[2rem] p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-pink-300 text-violet-950"><ClipboardCheck className="h-5 w-5" /></div><div><h3 className="text-xl font-extrabold text-white">{t.todayTasks}</h3><p className="text-sm text-white/65">{openTasks.length ? `${openTasks.length} ${t.openTasks}` : t.everythingDone}</p></div></div><div className="space-y-3">{data.tasks.length ? data.tasks.map(task => <TaskCard key={task.id} task={task} lang={lang} childMode onComplete={() => completeTask.mutate({ taskId: task.id })} />) : <EmptyState icon={<Sparkles />} text={t.noTasks} />}</div></div>
      <aside className="glass delayed-2 appear rounded-[2rem] p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-300 text-violet-950"><GraduationCap className="h-5 w-5" /></div><div><h3 className="text-xl font-extrabold text-white">{t.school}</h3><p className="text-sm text-white/65">{t.recentGrades}</p></div></div><div className="mt-5 space-y-3">{data.grades.length ? data.grades.map(grade => <div key={grade.id} className="rounded-2xl bg-white/[.09] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-white">{grade.subject}</p><p className="mt-1 text-sm text-white/65">{grade.assessment}</p></div><div className="rounded-xl bg-emerald-300 px-2.5 py-1 text-sm font-extrabold text-emerald-950">{Math.round(grade.score / grade.outOf * 100)}%</div></div><p className="mt-3 text-sm text-amber-100">{grade.score} / {grade.outOf}</p></div>) : <EmptyState icon={<BookOpen />} text={t.noGrades} />}</div></aside>
    </div>
  </section>;
}

function EmptyState({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="rounded-3xl border border-dashed border-white/25 bg-white/[.05] px-5 py-8 text-center text-sm leading-6 text-white/68"><span className="mx-auto mb-3 grid h-11 w-11 place-items-center rounded-2xl bg-white/[.1] text-white/80">{icon}</span>{text}</div>; }

function ParentDashboard({ data, lang }: { data: { children: ChildView[] }; lang: Language }) {
  const t = copy[lang];
  const utils = trpc.useUtils();
  const [activeChild, setActiveChild] = useState<ChildKey>("sandy");
  const [taskForm, setTaskForm] = useState({ title: "", description: "", category: "academic" as Category, dueDate: "", points: 10 });
  const [pinDraft, setPinDraft] = useState<Record<ChildKey, string>>({ sandy: "", celia: "" });
  const pendingReviews = useMemo(() => data.children.flatMap(dashboard => dashboard.tasks.filter(task => task.status === "completed").map(task => ({ task, childKey: dashboard.child.childKey }))), [data]);
  const [reviewTaskId, setReviewTaskId] = useState<number | undefined>(undefined);
  const [reviewRating, setReviewRating] = useState(5);
  const [reviewComment, setReviewComment] = useState("");
  const [gradeForm, setGradeForm] = useState({ subject: "", assessment: "", score: "", outOf: "100" });
  const selected = data.children.find(child => child.child.childKey === activeChild) ?? data.children[0];
  const createTask = trpc.family.parent.createTask.useMutation({ onSuccess: () => { toast.success(`${t.taskCreated} ${displayKid(activeChild, lang)}`); setTaskForm({ title: "", description: "", category: "academic", dueDate: "", points: 10 }); void utils.family.parent.overview.invalidate(); }, onError: () => toast.error(t.fillAll) });
  const setPin = trpc.family.parent.setPin.useMutation({ onSuccess: () => { toast.success(t.pinSaved); setPinDraft(current => ({ ...current, [activeChild]: "" })); void utils.family.parent.overview.invalidate(); }, onError: () => toast.error(t.invalidPin) });
  const submitReview = trpc.family.parent.reviewTask.useMutation({ onSuccess: () => { toast.success(t.reviewSaved); setReviewTaskId(undefined); setReviewComment(""); void utils.family.parent.overview.invalidate(); }, onError: () => toast.error(t.fillAll) });
  const recordGrade = trpc.family.parent.recordGrade.useMutation({ onSuccess: () => { toast.success(t.gradeSaved); setGradeForm({ subject: "", assessment: "", score: "", outOf: "100" }); void utils.family.parent.overview.invalidate(); }, onError: () => toast.error(t.fillAll) });

  function onCreateTask(event: FormEvent) { event.preventDefault(); if (!taskForm.title.trim()) return toast.error(t.fillAll); createTask.mutate({ childKey: activeChild, title: taskForm.title, description: taskForm.description || undefined, category: taskForm.category, dueDate: taskForm.dueDate ? new Date(taskForm.dueDate).toISOString() : undefined, points: Number(taskForm.points) }); }
  function onSetPin(event: FormEvent) { event.preventDefault(); const pin = pinDraft[activeChild]; if (!/^\d{4,8}$/.test(pin)) return toast.error(t.invalidPin); setPin.mutate({ childKey: activeChild, pin }); }
  function onRecordGrade(event: FormEvent) { event.preventDefault(); if (!gradeForm.subject || !gradeForm.assessment || !gradeForm.score || !gradeForm.outOf) return toast.error(t.fillAll); recordGrade.mutate({ childKey: activeChild, subject: gradeForm.subject, assessment: gradeForm.assessment, score: Number(gradeForm.score), outOf: Number(gradeForm.outOf) }); }
  function onReview(event: FormEvent) { event.preventDefault(); if (!reviewTaskId) return; submitReview.mutate({ taskId: reviewTaskId, rating: reviewRating, comment: reviewComment || undefined }); }

  return <section className="mx-auto max-w-7xl px-4 pb-16 pt-5 sm:px-6 lg:px-8">
    <header className="glass appear flex flex-col justify-between gap-5 rounded-[2rem] p-5 sm:flex-row sm:items-center sm:p-7"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-amber-200 to-orange-300 text-violet-950 shadow-lg"><Crown className="h-7 w-7" /></div><div><p className="wide-label text-[10px] text-white/64">{t.welcomeBack}</p><h2 className="hero-title mt-1 text-3xl font-extrabold text-white sm:text-4xl">{t.parentPanel}</h2></div></div><Pill><ShieldCheck className="h-3.5 w-3.5 text-emerald-200" />{t.secure}</Pill></header>
    <div className="mt-6 grid gap-4 md:grid-cols-2">{data.children.map((dashboard, index) => { const kid = dashboard.child.childKey; const open = dashboard.tasks.filter(task => task.status === "open").length; return <button key={kid} onClick={() => setActiveChild(kid)} className={`kid-card round-button appear ${index ? "delayed-1" : ""} min-h-[168px] rounded-[1.75rem] border p-5 text-start ${activeChild === kid ? "border-white/50 bg-white/[.19]" : "border-white/17 bg-white/[.08]"}`}><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><KidAvatar kid={kid} /><div><h3 className="text-xl font-extrabold text-white">{displayKid(kid, lang)}</h3><p className="text-sm text-white/66">{dashboard.child.age} {t.years}</p></div></div><span className="rounded-2xl bg-amber-200 px-2.5 py-1 text-sm font-bold text-violet-950">{dashboard.child.points} {t.points}</span></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs text-white/73"><span>{t.weeklyProgress}</span><span>{dashboard.progress}%</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${dashboard.progress}%` }} /></div><p className="mt-3 text-sm text-white/74">{open ? `${open} ${t.openTasks}` : t.everythingDone}</p></div></div></button>; })}</div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_.95fr_1.05fr]">
      <form onSubmit={onCreateTask} className="glass delayed-1 appear rounded-[2rem] p-5 sm:p-6"><SectionHeading icon={<Plus />} title={t.createTask} subtitle={`${t.assignTo}: ${displayKid(activeChild, lang)}`} /><div className="mt-5 space-y-3"><input value={taskForm.title} onChange={event => setTaskForm({ ...taskForm, title: event.target.value })} className="family-input" placeholder={t.taskTitle} /><textarea value={taskForm.description} onChange={event => setTaskForm({ ...taskForm, description: event.target.value })} className="family-input min-h-[72px] resize-y" placeholder={t.taskDescription} /><div className="grid grid-cols-2 gap-3"><select value={taskForm.category} onChange={event => setTaskForm({ ...taskForm, category: event.target.value as Category })} className="family-input family-select"><option value="academic">{t.academic}</option><option value="household">{t.household}</option><option value="hygiene">{t.hygiene}</option><option value="organization">{t.organization}</option></select><input value={taskForm.points} onChange={event => setTaskForm({ ...taskForm, points: Number(event.target.value) })} className="family-input" type="number" min="1" max="100" aria-label={t.reward} /></div><input value={taskForm.dueDate} onChange={event => setTaskForm({ ...taskForm, dueDate: event.target.value })} className="family-input" type="datetime-local" aria-label={t.deadline} /><Button type="submit" disabled={createTask.isPending} className="round-button h-11 w-full rounded-2xl bg-gradient-to-r from-pink-300 to-fuchsia-300 font-bold text-violet-950 hover:from-pink-200 hover:to-fuchsia-200">{createTask.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="me-2 h-4 w-4" />}{t.addTask}</Button></div></form>
      <form onSubmit={onReview} className="glass delayed-2 appear rounded-[2rem] p-5 sm:p-6"><SectionHeading icon={<MessageCircleHeart />} title={t.reviewWork} subtitle={t.chooseTaskHelp} /><div className="mt-5 space-y-3">{pendingReviews.length ? <><select value={reviewTaskId ?? ""} onChange={event => setReviewTaskId(Number(event.target.value) || undefined)} className="family-input family-select"><option value="">{t.chooseTask}</option>{pendingReviews.map(item => <option key={item.task.id} value={item.task.id}>{displayKid(item.childKey, lang)} — {item.task.title}</option>)}</select><div className="rounded-2xl bg-slate-950/[.19] p-3"><p className="mb-2 text-sm font-semibold text-white/75">{t.rating}</p><div className="flex gap-1.5">{[1,2,3,4,5].map(star => <button type="button" onClick={() => setReviewRating(star)} key={star} className={`star-button ${star <= reviewRating ? "text-amber-200" : "text-white/30"}`} aria-label={`${star} stars`}><Star className="h-7 w-7 fill-current" /></button>)}</div></div><textarea value={reviewComment} onChange={event => setReviewComment(event.target.value)} className="family-input min-h-[75px] resize-y" placeholder={t.writeNote} /><Button type="submit" disabled={!reviewTaskId || submitReview.isPending} className="round-button h-11 w-full rounded-2xl bg-gradient-to-r from-amber-200 to-orange-300 font-bold text-violet-950 hover:from-amber-100 hover:to-orange-200">{submitReview.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Star className="me-2 h-4 w-4 fill-current" />}{t.submitReview}</Button></> : <EmptyState icon={<MessageCircleHeart />} text={t.noReviews} />}</div></form>
      <div className="glass delayed-3 appear rounded-[2rem] p-5 sm:p-6"><SectionHeading icon={<GraduationCap />} title={t.trackLearning} subtitle={`${displayKid(activeChild, lang)} · ${t.recentGrades}`} /><form onSubmit={onRecordGrade} className="mt-5 space-y-3"><div className="grid grid-cols-2 gap-3"><input value={gradeForm.subject} onChange={event => setGradeForm({ ...gradeForm, subject: event.target.value })} className="family-input" placeholder={t.subject} /><input value={gradeForm.assessment} onChange={event => setGradeForm({ ...gradeForm, assessment: event.target.value })} className="family-input" placeholder={t.assessment} /></div><div className="grid grid-cols-2 gap-3"><input value={gradeForm.score} onChange={event => setGradeForm({ ...gradeForm, score: event.target.value })} className="family-input" placeholder={t.score} type="number" min="0" /><input value={gradeForm.outOf} onChange={event => setGradeForm({ ...gradeForm, outOf: event.target.value })} className="family-input" placeholder={t.total} type="number" min="1" /></div><Button type="submit" disabled={recordGrade.isPending} className="round-button h-11 w-full rounded-2xl bg-gradient-to-r from-violet-300 to-indigo-300 font-bold text-violet-950 hover:from-violet-200 hover:to-indigo-200">{recordGrade.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <BookOpen className="me-2 h-4 w-4" />}{t.recordGrade}</Button></form>{selected?.grades.length ? <div className="mt-5 space-y-2">{selected.grades.slice(0, 3).map(grade => <div key={grade.id} className="flex justify-between rounded-2xl bg-white/[.08] px-3 py-2.5 text-sm"><span className="font-semibold text-white">{grade.subject}</span><span className="font-bold text-amber-200">{grade.score}/{grade.outOf}</span></div>)}</div> : null}</div>
    </div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
      <div className="glass rounded-[2rem] p-5 sm:p-6"><SectionHeading icon={<ClipboardCheck />} title={`${displayKid(activeChild, lang)} · ${t.todayTasks}`} subtitle={t.status} /><div className="mt-5 space-y-3">{selected?.tasks.length ? selected.tasks.map(task => <TaskCard key={task.id} task={task} lang={lang} />) : <EmptyState icon={<Sparkles />} text={t.noTasks} />}</div></div>
      <form onSubmit={onSetPin} className="glass rounded-[2rem] p-5 sm:p-6"><SectionHeading icon={<KeyRound />} title={t.security} subtitle={selected?.child.hasPin ? t.pinReady : t.pinNeeded} /><p className="mt-5 text-sm leading-6 text-white/70">{t.setPinsFirst}</p><div className="mt-4 flex gap-3"><input value={pinDraft[activeChild]} onChange={event => setPinDraft({ ...pinDraft, [activeChild]: event.target.value.replace(/\D/g, "") })} className="family-input" placeholder={t.enterPin} inputMode="numeric" maxLength={8} type="password" /><Button type="submit" disabled={setPin.isPending} className="round-button h-auto shrink-0 rounded-2xl bg-white/15 px-4 font-bold text-white hover:bg-white/23">{setPin.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <KeyRound className="h-4 w-4" />}</Button></div></form>
    </div>
  </section>;
}

function SectionHeading({ icon, title, subtitle }: { icon: React.ReactNode; title: string; subtitle: string }) { return <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/[.13] text-amber-100">{icon}</span><div><h3 className="font-extrabold text-white">{title}</h3><p className="mt-0.5 text-xs leading-4 text-white/60">{subtitle}</p></div></div>; }

function ChildLogin({ lang, onBack }: { lang: Language; onBack: () => void }) {
  const t = copy[lang]; const utils = trpc.useUtils(); const [kid, setKid] = useState<ChildKey>("sandy"); const [pin, setPin] = useState("");
  const login = trpc.family.child.login.useMutation({ onSuccess: () => { toast.success(`${t.welcomeBack}, ${displayKid(kid, lang)}!`); void utils.family.child.me.invalidate(); }, onError: () => toast.error(t.setPinsFirst) });
  function onSubmit(event: FormEvent) { event.preventDefault(); if (!/^\d{4,8}$/.test(pin)) return toast.error(t.invalidPin); login.mutate({ childKey: kid, pin }); }
  return <section className="mx-auto flex min-h-[calc(100vh-92px)] max-w-xl items-center px-4 py-8 sm:px-6"><div className="glass appear w-full rounded-[2rem] p-6 sm:p-9"><button onClick={onBack} className="round-button inline-flex items-center gap-1.5 text-sm font-semibold text-white/75 hover:text-white"><ChevronLeft className="h-4 w-4 rtl:rotate-180" />{t.back}</button><div className="mt-7 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-[1.5rem] bg-gradient-to-br from-pink-300 to-violet-300 text-violet-950"><UserRound className="h-8 w-8" /></div><p className="wide-label mt-5 text-[10px] text-white/65">{t.secure}</p><h2 className="hero-title mt-2 text-4xl font-extrabold text-white">{t.childLogin}</h2><p className="mx-auto mt-3 max-w-sm leading-7 text-white/70">{t.childIntro}</p></div><form onSubmit={onSubmit} className="mx-auto mt-7 max-w-sm space-y-4"><p className="text-sm font-semibold text-white/80">{t.selectChild}</p><div className="grid grid-cols-2 gap-3">{(["sandy", "celia"] as ChildKey[]).map(key => <button key={key} onClick={() => setKid(key)} type="button" className={`round-button flex items-center gap-2 rounded-2xl border p-3 text-start ${kid === key ? "border-white/55 bg-white/[.18]" : "border-white/16 bg-white/[.07]"}`}><KidAvatar kid={key} size="sm" /><span className="font-bold text-white">{displayKid(key, lang)}</span></button>)}</div><label className="block text-sm font-semibold text-white/80">{t.privatePin}<input value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, ""))} className="family-input mt-2 text-center tracking-[.6em]" placeholder="••••" inputMode="numeric" maxLength={8} type="password" /></label><Button type="submit" disabled={login.isPending} className="round-button h-12 w-full rounded-2xl bg-gradient-to-r from-amber-200 to-orange-300 font-bold text-violet-950 hover:from-amber-100 hover:to-orange-200">{login.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <LogIn className="me-2 h-4 w-4" />}{t.continue}</Button></form></div></section>;
}

function Hero({ lang, onParent, onChildren, isAuthenticated, logout }: { lang: Language; onParent: () => void; onChildren: () => void; isAuthenticated: boolean; logout: () => void }) { const t = copy[lang]; return <section className="mx-auto flex min-h-[calc(100vh-92px)] max-w-6xl items-center px-4 py-10 sm:px-6 lg:px-8"><div className="w-full text-center"><Pill><Sparkles className="h-3.5 w-3.5 text-amber-200" />{t.secure}</Pill><p className="wide-label mt-6 text-[10px] font-semibold text-white/72 sm:text-xs">{t.eyebrow}</p><h1 className="hero-title mx-auto mt-4 max-w-4xl whitespace-pre-line text-5xl font-extrabold leading-[.98] text-white sm:text-7xl lg:text-8xl">{t.heroTitle}</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-white/80 sm:text-lg">{t.heroText}</p><div className="mx-auto mt-10 grid max-w-2xl gap-3 sm:grid-cols-2"><button onClick={onParent} className="glass round-button group flex min-h-[106px] items-center gap-4 rounded-3xl p-5 text-start hover:bg-white/[.22]"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-amber-200 to-orange-300 text-violet-950"><Crown className="h-7 w-7" /></span><span><strong className="block text-lg text-white">{t.parentDoor}</strong><small className="mt-1 block leading-5 text-white/68">{t.parentHint}</small></span></button><button onClick={onChildren} className="glass round-button group flex min-h-[106px] items-center gap-4 rounded-3xl p-5 text-start hover:bg-white/[.22]"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-pink-300 to-violet-300 text-violet-950"><WandSparkles className="h-7 w-7" /></span><span><strong className="block text-lg text-white">{t.childrenDoor}</strong><small className="mt-1 block leading-5 text-white/68">{t.readyToGrow}</small></span></button></div>{isAuthenticated && <button onClick={logout} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-white/72 hover:text-white"><LogOut className="h-4 w-4" />{t.signOut}</button>}</div></section>; }

export default function Home() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const [lang, setLang] = useState<Language>(() => (localStorage.getItem("family-language") as Language) || "ar");
  const [screen, setScreen] = useState<Screen>("welcome");
  const t = copy[lang];
  const parentQuery = trpc.family.parent.overview.useQuery(undefined, { enabled: Boolean(isAuthenticated && user?.role === "admin") });
  const childQuery = trpc.family.child.me.useQuery();
  const childLogout = trpc.family.child.logout.useMutation({ onSuccess: () => void childQuery.refetch() });
  useEffect(() => { localStorage.setItem("family-language", lang); document.documentElement.lang = lang; document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"; }, [lang]);
  function openParent() { if (!isAuthenticated) { startLogin(); return; } setScreen("parent"); }
  function openChildren() { setScreen("children"); }
  const isAdmin = isAuthenticated && user?.role === "admin";
  return <div className="family-shell" dir={lang === "ar" ? "rtl" : "ltr"}><div className="mesh-layer" /><div className="noise" /><nav className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-5 sm:px-6 lg:px-8"><button onClick={() => setScreen("welcome")} className="group flex items-center gap-2 text-start"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/16 text-amber-200 transition-transform group-hover:rotate-6"><Sparkles className="h-5 w-5" /></span><span><strong className="block text-sm leading-tight text-white sm:text-base">{t.brand}</strong><small className="block text-[10px] text-white/58">{t.secure}</small></span></button><div className="flex items-center gap-2"><button onClick={() => setLang(lang === "ar" ? "en" : "ar")} className="round-button inline-flex h-10 items-center gap-2 rounded-2xl border border-white/20 bg-white/[.1] px-3 text-xs font-bold text-white hover:bg-white/[.19]"><Languages className="h-4 w-4" />{t.language}</button>{childQuery.data && screen === "children" && <button onClick={() => childLogout.mutate()} className="round-button grid h-10 w-10 place-items-center rounded-2xl border border-white/20 bg-white/[.1] text-white hover:bg-white/[.19]" aria-label={t.signOut}><LogOut className="h-4 w-4" /></button>}</div></nav>{loading ? <div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin text-white" /></div> : screen === "parent" ? (isAdmin ? parentQuery.isLoading ? <div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin text-white" /></div> : parentQuery.data ? <ParentDashboard data={parentQuery.data as { children: ChildView[] }} lang={lang} /> : <Hero lang={lang} onParent={openParent} onChildren={openChildren} isAuthenticated={isAuthenticated} logout={logout} /> : <section className="mx-auto flex min-h-[60vh] max-w-lg items-center px-4"><div className="glass w-full rounded-[2rem] p-7 text-center"><ShieldCheck className="mx-auto h-12 w-12 text-amber-200" /><h2 className="hero-title mt-4 text-3xl font-extrabold text-white">{t.parentDoor}</h2><p className="mt-3 leading-7 text-white/72">{t.notAdmin}</p><button onClick={() => setScreen("welcome")} className="round-button mt-6 text-sm font-bold text-white underline underline-offset-4">{t.back}</button></div></section>) : screen === "children" ? childQuery.isLoading ? <div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin text-white" /></div> : childQuery.data ? <ChildDashboard data={childQuery.data as ChildView} lang={lang} onBack={() => setScreen("welcome")} /> : <ChildLogin lang={lang} onBack={() => setScreen("welcome")} /> : <Hero lang={lang} onParent={openParent} onChildren={openChildren} isAuthenticated={isAuthenticated} logout={logout} />}</div>;
}
